name: her2
channels:
  - pytorch
dependencies:
  - pip
  - numpy=1.21.3
  - pandas=1.3.4
  - Pillow=8.4.0
  - scikit-learn=1.0.1
  - scikit-image=0.14.3
  - pytorch=1.10.0
  - torchvision=0.11.1
  - pip:
    - opencv-python